baseURL = 'http://mishaboar.org/'
defaultContentLanguage = "en"
languageCode = 'en-us'
title = 'Mishaboar'
theme = 'LoveIt'

[params]
  # LoveIt theme version
  version = "0.2.X"


  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/avatar.jpg"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Half man, half boar, all cannoli. And Dogecoin, of course."
      # subtitle shown in home page
      subtitle = "Dogecoin news, mostly on Twitter. Dogecoin node operator. Unbiased, clear, no hype - encouraging day to day use. Ask me questions. The dip? But a scratch."
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = false
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/images/avatarcircle.png"
      # title name
      name = "Mishaboar"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false



 # Social config about the author
  [params.social]
    Twitter = "Mishaboar"
    Reddit = "mishaboar"  
    GitHub = "mishaboar"
    Email = "mishaboar@protonmail.com"
    RSS = true # LoveIt NEW | 0.2.0


[menu]
  [[menu.main]]
    identifier = "twitter"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Twitter"
    url = "https://twitter.com/mishaboar/"
    # title will be shown when you hover on this menu link
    title = "On Twitter"
    weight = 1
  [[menu.main]]
    identifier = "nodes"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Nodes"
    url = "https://nodes.dogebeard.com/"
    # title will be shown when you hover on this menu link
    title = "Nodes 1-5"
    weight = 2

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
